#ifndef DLLOGGING_H
#define DLLOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(dlApp)
Q_DECLARE_LOGGING_CATEGORY(dlDb)
Q_DECLARE_LOGGING_CATEGORY(dlRepo)
Q_DECLARE_LOGGING_CATEGORY(dlService)
Q_DECLARE_LOGGING_CATEGORY(dlQuiz)

#endif // DLLOGGING_H
